//lista de termos que não podem
//ele esta juntando tudo, e nao esta puxando pois tem que colocar
//para ele puxar no meio das palavras

//import { companies } from "./invalid"

const companiesRules =  [
  "sim",
  "nao",
  "pag",
  "123milhas",
  "123 milhas",
  "uber",
  "ton",
  "amazon",
  "stone",
  "cred",
  "pay",
  "emp",
  "emprestimos",
  "tem como?",
  "tem",
  "credito",
  "ola",
  "boa tarde",
  "boa",
  "casas bahia",
  "casa bahia",
  "pg",
  "magazineluiza",
  "magazine luiza",
  "boto",
  "coloco",
  "como",
  "razao",
  "social",
  "razaosocial",
  "oi",
  "americanas",
  "americana",
  "netshoes",
  "shopee",
  "apple"]

//lita de nomes fantasias a serem lisados

//import { companiesName } from "./companiesName"

const companiesToCheck = [
  "My lavish closet",
  "Dona D'ela",
  "Mercado nalva",
  "NiviaTravasso",
  "Space Apolo",
  "AD Crav. VC",
  "Budega",
  "JONAS FIBRA",
  "Gesso isrrael",
  "Nildo Moreno",
  "Sim",
  "ton",
  "Ssconstrucoes",
  "Casas Bahia",
  "Impacto",
  "BGC",
  "Rafel",
  "Cia telhados",
  "Compras TON",
  "ILUMIN S S",
  "Automóveis",
  "Marechal tech",
  "Sdmodaintima",
  "Rei do óleo",
  "Espaço beleza",
  "Portaldventos",
  "Point razaosocial vip",
  "Rodriguinho",
  "Stúdio R.A",
  "JL PROTECTION",
  "Anatshirts",
  "Maryás",
  "Nena sabores",
  "Studio H.",
  "Ameimport",
  "Borracharia",
  "L'ARRËE-ES",
  "General Sena",
  "BOXIMPORTS",
  "Uau Limpeza",
  "Sim",
  "Pinhal Smart",
  "Karla Vargas",
  "Bruka Iphones",
  "Vet Felipe",
  "Churrasquinho",
  "AG BABY",
  "Pingo de ouro",
  "LR VARIEDADE",
  "Thiago.import",
  "Panif Isabely",
  "pudim da Day",
  "Canossa",
  "J & J ice",
  "Rota Outlet",
  "Ink Móveis",
  "Pedra cell",
  "Moto peças",
  "Inove Ne",
  "UnifixStore",
  "Jailson motos",
  "LabSantos",
  "Hotel Raijós",
  "Bela Store",
  "YC ton",
  "GMC serv",
  "M.semijoias",
  "Hortência",
  "MILITARY",
  "Vendas",
  "Bity Store",
  "OdontoLux",
  "Studio LF",
  "Gra Bout&Conf",
  "Informática",
  "Alpha Kids",
  "AMBEVDCENTRAL",
  "Deposito rj",
  "Assvariedades",
  "Top Brilho",
  "Lion Of Judah",
  "Ilumina",
  "@lunaturablz",
  "Bom dia",
  "Sim",
  "@Use.Maintain",
  "Charm",
  "Nigro Viagens",
  "Estrela",
  "J.N comércio",
  "Edy-burguer",
  "HUDY GRÁFICA",
  "Tecnologia 10",
  "Via Aquarium",
  "Nail art",
  "D_makes",
  "Better Tech",
  "LM STORE",
  "LR Store",
  "Arvariedades",
  "StudioTatiane",
  "Arte tapete",
  "EduArtes97",
  "NaModaComaLay",
  "MpDiversos",
  "99EXPRESS",
  "Netshoes SP",
  "Lidia - Make",
  "L.Almeida",
  "GSKROUPAS",
  "Studio MCR",
  "Rogério",
  "Supermercado",
  "W N",
  "Pneus S.A",
  "OFC 2 IRMÃOS",
  "Taxi gilson",
  "Mãe Gilda",
  "GabiBronze",
  "Bella_.chic_",
  "SALVATTORE",
  "CintaCirurgic",
  "NB Store Moda",
  "Milla store",
  "Bavaresco",
  "REALEZA modas",
  "BATISTA DESPA",
  "Lion estofad",
  "Ir. Nogueira",
  "Fernanda Braz",
  "Loja de casa",
  "Lafvariedades",
  "Pcds2789",
  "DS Designer",
  "John Jeferson",
  "Dj variedades",
  "Perfumes Vini",
  "Nayde berr",
  "LAFashion",
  "Otica",
  "YAHCHURCH",
  "PontodaRacao",
  "Patríck",
  "MercadoCarmo",
  "Danipereira",
  "Graficatimao",
  "GMJ_Negócios",
  "Salão Beleza",
  "Inter store",
  "Helena Gomes",
  "Ton pag ton",
  "Impacto",
  "Mm Barreto",
  "RF Gráfica",
  "Mix de Brilho",
  "Tsscam",
  "TECNOVIDROS",
  "Está errado",
  "Fazendinha",
  "W Imports",
  "JC Doçuras",
  "AMORA CLOSET",
  "Império",
  "Shopee loja",
  "GMF emp",
  "ChocolateShow",
  "TETÉ",
  "Santa Rita",
  "Eu quero Neta",
  "Laggil",
  "Diogo tatoo",
  "Ella vic",
  "JD BARBER",
  "CarlimAntenas",
  "Lucas Martins",
  "Glaucio",
  "Beleza AR",
  "RN COMÉRCIO",
  "Fashion kids",
  "Aline&Renato",
  "Jane Kelly",
  "BARBEARIA",
  "Francine",
  "Cia & Reforma",
  "Ton alves me",
  "Eletro Cell",
  "DES,MODA SURF",
  "MATTEO",
  "MIA Tech",
  "Vendas Ton",
  "Tay",
  "Carreteiro",
  "Pro Material",
  "ShoppingOn084",
  "Luis",
  "Parceiro Ton",
  "Rogériovendas",
  "Rl mercado",
  "Me ajuda",
  "VENDAS TON",
  "Bett",
  "Auto card",
  "FB VENDAS",
  "Relocell",
  "Morgante LTDA",
  "Maxinet Cia",
  "Sabrina RSO",
  "Outlet 074",
  "Danielle.C.S",
  "Wesley Barber",
  "M.vinicius",
  "ML BUTIQUE",
  "Igor Táxi",
  "Salada gomes",
  "Empório Vila",
  "FEIRA",
  "Rennam Hair",
  "Coenja",
  "Service fast",
  "Aurora Calhas",
  "Centro Moda",
  "tziumotopecas",
  "LAP Racing",
  "Impera Man"
  ]



//função de comparação 
//estamos pegando o nome das empresas e colocando tudo minusculo além de remover os espaços
// isso vai aumentar o range de possíveis combinações que vamos pegar
// tipo MagazineLuiz, PontoFrio, ASSAI

const mapFunction = item => item.toLowerCase().replace(" ", "")

//trasnformação dos arrays
const mappedCompaniesRules = companiesRules.map(mapFunction)
const mappedCompaniesToCheck = companiesToCheck.map(mapFunction)


//comparação e criação de listas de nomes fantasia irregulares
const irregularList = mappedCompaniesToCheck.filter(
  item => {
    if (mappedCompaniesRules.some(company => item.includes(company)))
      return item
//      const result = mappedCompaniesRules.some(company => companiesRules.includes(item))
//      return result
  }
)

//printa no console as empresas irregulares 
console.log('irregularList', irregularList)